### ISSUE TITLE
Textile Desire Not Counting Textile stock

### ISSUE THREAD

**Issue by LupineWitch** [Sielfyr/Dream#1]
I have a pawn with desire "Wants textile stock" I have to gather 35 leather or textile stuff, despite having over 311 units of camel hide, the wishe's counter is stuck on 14. All items are in stockpile, inside home zone.

**Comment by Sielfyr** [comment]
It's a wish where you need to increase your textile stock by 35, you need 35 more unit of textile than when the wish was made. 

I will update the wish label to be more clear.
